project_id = "rt-presentation-feedback-api"

[api]
enabled = true
port = 54331
schemas = ["public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db.migrations]
# If disabled, migrations will be skipped during a db push or reset.
enabled = true

[db]
port = 54332
shadow_port = 54320
major_version = 15

[db.seed]
enabled = true
sql_paths = ["./seed.sql"]

[studio]
enabled = true
port = 54333

[analytics]
enabled = false